### ISSUE TITLE
Better communication

### ISSUE THREAD

**Issue by lighthousand** [javascript-tutorial/ro.javascript.info#19]
We use slack here : https://join.slack.com/t/rojavascriptt-blb2786/shared_invite/enQtNzE4MjU3Njk1ODc2LWQ4NjRhYzMzNTMyMmNhOTI4M2FjZjBlM2YwMTIxMGFmNDIwZGU1MzU2M2MyMGI5YzNiY2NiY2FiMTAwOWJiNzM

**Comment by bogdanbacosca** [comment]
Link is no longer active `To join this workspace, you’ll need to ask the person who originally invited you for a new link.`

**Comment by bogdanbacosca** [comment]
Will explore this further. Issue closed for being out of date.
