### ISSUE TITLE
Recreated the repo

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/ro.javascript.info#2]
Renamed the previous repo to https://github.com/javascript-tutorial/ro-old.javascript.info, as it was not branched off of the main en.javascript.info repo.

So auto-sync scripts couldn't run on it.

Please transfer the translation to this repo.

Sorry for inconvenience, translation being a branch of the English repo allows for future auto-sync of changes.

**Comment by lighthousand** [comment]
Ok, so I will move the latest translations on https://github.com/javascript-tutorial/ro.javascript.info, then ?

**Comment by lighthousand** [comment]
From what I see, actually I'll move all the current translations.

**Comment by iliakan** [comment]
Yes, please. You can also see what changed in the English since you created the Romanian repo by:
```
// 5ba5f8b7 is a commit from 21 Nov 2018, about the time you created Romanian repo
git diff 5ba5f8b7..
```

Some changes are just wording, some are important.

**Comment by lighthousand** [comment]
Yes, I will take a look at the changes and I will modify what needs to be modified.

**Comment by bogdanbacosca** [comment]
Is this still relevant?
