### ISSUE TITLE
GitKraken access

### ISSUE THREAD

**Issue by lighthousand** [javascript-tutorial/ro.javascript.info#3]
@iliakan, can you please provide me access to the organization for GitKraken ?

**Comment by iliakan** [comment]
Why is that needed?

**Comment by lighthousand** [comment]
It won't be needed anymore. I initially tried to make a different branch on this repository and then tried to make pull requests and merge to master. The access was need when i would push the new created branch, to the remote repo. But now i forked the repo and i will make pull requests from the fork to the main repo.

**Comment by lighthousand** [comment]
Sorry for wasting your time :)
